Create Table BOOKS ( ID integer PRIMARY KEY, TITLE varchar(100), AUTHOR varchar(50), RELEASE_DATE text, NUM_OF_PAGES integer, GENRE varchar(50), NUM_OF_COPIES integer, PRICE double); 

Insert Into BOOKS ( ID, TITLE, AUTHOR, RELEASE_DATE, NUM_OF_PAGES, GENRE, NUM_OF_COPIES, PRICE) Values ( null,'Ezoteryczny Poznań','Aleksandra Romaniuk','1975-10-12',669,'Kryminał',4,40.99 );
Insert Into BOOKS ( ID, TITLE, AUTHOR, RELEASE_DATE, NUM_OF_PAGES, GENRE, NUM_OF_COPIES, PRICE) Values ( null,'Koniec narodu','Dominik Kwiatkowski','1984-11-20',266,'Literatura faktu',17,50.99 );
Insert Into BOOKS ( ID, TITLE, AUTHOR, RELEASE_DATE, NUM_OF_PAGES, GENRE, NUM_OF_COPIES, PRICE) Values ( null,'Kamieniołomy','Melissa Beck','1988-01-02',450,'Thriller',103,19.99 );
Insert Into BOOKS ( ID, TITLE, AUTHOR, RELEASE_DATE, NUM_OF_PAGES, GENRE, NUM_OF_COPIES, PRICE) Values ( null,'Donikąd','Anna Hawro','1962-10-15',521,'Science-fiction',43,59.99 );
Insert Into BOOKS ( ID, TITLE, AUTHOR, RELEASE_DATE, NUM_OF_PAGES, GENRE, NUM_OF_COPIES, PRICE) Values ( null,'Znajomi mego ojca','Reuben Walsh','2016-03-04',387,'Literatura faktu',45,45.99 );
Insert Into BOOKS ( ID, TITLE, AUTHOR, RELEASE_DATE, NUM_OF_PAGES, GENRE, NUM_OF_COPIES, PRICE) Values ( null,'Podróżnicy z krainy Z','Małgorzata Stadnik','1971-12-01',380,'Fantastyka',13,32.59 );
Insert Into BOOKS ( ID, TITLE, AUTHOR, RELEASE_DATE, NUM_OF_PAGES, GENRE, NUM_OF_COPIES, PRICE) Values ( null,'Terranova 3','Zara Martinez','2000-10-02',197,'Fantastyka',4,19.89 );
Insert Into BOOKS ( ID, TITLE, AUTHOR, RELEASE_DATE, NUM_OF_PAGES, GENRE, NUM_OF_COPIES, PRICE) Values ( null,'Zaufaj','Anna Hawro','2007-05-04',488,'Poezja',6,25.49 );
Insert Into BOOKS ( ID, TITLE, AUTHOR, RELEASE_DATE, NUM_OF_PAGES, GENRE, NUM_OF_COPIES, PRICE) Values ( null,'Jak poznałam Anthonego L.','Isla Dunn','1993-01-05',642,'Romans',11,24.99 );
Insert Into BOOKS ( ID, TITLE, AUTHOR, RELEASE_DATE, NUM_OF_PAGES, GENRE, NUM_OF_COPIES, PRICE) Values ( null,'Kategorycznie lirycznie','Aleksander Jankowski','1994-08-10',562,'Poezja',23,25.99 );
Insert Into BOOKS ( ID, TITLE, AUTHOR, RELEASE_DATE, NUM_OF_PAGES, GENRE, NUM_OF_COPIES, PRICE) Values ( null,'Na krańcu świata w dniu narodzin','Samson Durand','1986-06-01',523,'Literatura obyczajowa',20,49.99 );
Insert Into BOOKS ( ID, TITLE, AUTHOR, RELEASE_DATE, NUM_OF_PAGES, GENRE, NUM_OF_COPIES, PRICE) Values ( null,'Pięknie i drogo','Eloise Arnold','1967-06-05',551,'Literatura obyczajowa',0,59.99 );
Insert Into BOOKS ( ID, TITLE, AUTHOR, RELEASE_DATE, NUM_OF_PAGES, GENRE, NUM_OF_COPIES, PRICE) Values ( null,'Red Velvet','Georgina Chapman','1960-03-05',306,'Literatura obyczajowa',1,23.99 );
Insert Into BOOKS ( ID, TITLE, AUTHOR, RELEASE_DATE, NUM_OF_PAGES, GENRE, NUM_OF_COPIES, PRICE) Values ( null,'Ostatnie spotkanie','Lara Owen','2002-03-10',279,'Horror',0,29.99 );
Insert Into BOOKS ( ID, TITLE, AUTHOR, RELEASE_DATE, NUM_OF_PAGES, GENRE, NUM_OF_COPIES, PRICE) Values ( null,'Pierwszy raz z siekierą','Zara Martinez','1989-02-20',620,'Kryminał',9,45.99 );
Insert Into BOOKS ( ID, TITLE, AUTHOR, RELEASE_DATE, NUM_OF_PAGES, GENRE, NUM_OF_COPIES, PRICE) Values ( null,'Krasnopol','Oscar Logan','2017-09-01',440,'Fantastyka',24,39.99 );
Insert Into BOOKS ( ID, TITLE, AUTHOR, RELEASE_DATE, NUM_OF_PAGES, GENRE, NUM_OF_COPIES, PRICE) Values ( null,'W tajemnicy przed faktem','Oscar Logan','1992-03-14',483,'Literatura obyczajowa',33,69.49 );
Insert Into BOOKS ( ID, TITLE, AUTHOR, RELEASE_DATE, NUM_OF_PAGES, GENRE, NUM_OF_COPIES, PRICE) Values ( null,'To nie tak','Ibrahim Morrison','2007-05-03',265,'Kryminał',17,42.99 );
Insert Into BOOKS ( ID, TITLE, AUTHOR, RELEASE_DATE, NUM_OF_PAGES, GENRE, NUM_OF_COPIES, PRICE) Values ( null,'Henryk VI od innej strony','Lara Owen','1972-11-06',187,'Powieść historyczna',6,19.99 );
Insert Into BOOKS ( ID, TITLE, AUTHOR, RELEASE_DATE, NUM_OF_PAGES, GENRE, NUM_OF_COPIES, PRICE) Values ( null,'Wyprawa w stronę dalekich krain','Roman Popov','2015-08-16',299,'Fantastyka',2,28.99 );
Insert Into BOOKS ( ID, TITLE, AUTHOR, RELEASE_DATE, NUM_OF_PAGES, GENRE, NUM_OF_COPIES, PRICE) Values ( null,'In my arms: w mych ramionach','Samson Durand','2001-01-24',399,'Poezja',67,33.89 );
Insert Into BOOKS ( ID, TITLE, AUTHOR, RELEASE_DATE, NUM_OF_PAGES, GENRE, NUM_OF_COPIES, PRICE) Values ( null,'Dzień z życia Jakuba','Oskar Wojciechowski','1999-12-31',652,'Powieść młodzieżowa',13,33.49 );
Insert Into BOOKS ( ID, TITLE, AUTHOR, RELEASE_DATE, NUM_OF_PAGES, GENRE, NUM_OF_COPIES, PRICE) Values ( null,'Ostatni będą ostatni','Dominik Kwiatkowski','1981-11-14',187,'Horror',5,39.99 );
Insert Into BOOKS ( ID, TITLE, AUTHOR, RELEASE_DATE, NUM_OF_PAGES, GENRE, NUM_OF_COPIES, PRICE) Values ( null,'Sacrum','Traci Bowen','1998-11-15',249,'Thriller',33,29.99 );
Insert Into BOOKS ( ID, TITLE, AUTHOR, RELEASE_DATE, NUM_OF_PAGES, GENRE, NUM_OF_COPIES, PRICE) Values ( null,'Przybysze z nikąd','Bruno Mazur','2011-10-09',315,'Science-fiction',0,99.99 );
Insert Into BOOKS ( ID, TITLE, AUTHOR, RELEASE_DATE, NUM_OF_PAGES, GENRE, NUM_OF_COPIES, PRICE) Values ( null,'Ta kraina','Marie Knight','1986-05-01',517,'Powieść historyczna',0,29.99 );
Insert Into BOOKS ( ID, TITLE, AUTHOR, RELEASE_DATE, NUM_OF_PAGES, GENRE, NUM_OF_COPIES, PRICE) Values ( null,'Niedowiarek','Jacques Bernard','1979-06-01',259,'Horror',8,45.49 );
Insert Into BOOKS ( ID, TITLE, AUTHOR, RELEASE_DATE, NUM_OF_PAGES, GENRE, NUM_OF_COPIES, PRICE) Values ( null,'Ląd upragniony','Dominik Kwiatkowski','1986-03-15',241,'Romans',5,9.49 );
Insert Into BOOKS ( ID, TITLE, AUTHOR, RELEASE_DATE, NUM_OF_PAGES, GENRE, NUM_OF_COPIES, PRICE) Values ( null,'Czasu nie cofniesz','Isobel Vasquez','1988-04-30',347,'Science-fiction',23,25.99 );
Insert Into BOOKS ( ID, TITLE, AUTHOR, RELEASE_DATE, NUM_OF_PAGES, GENRE, NUM_OF_COPIES, PRICE) Values ( null,'Niemożliwy obrót zdarzeń','Sara Schneider','1985-03-03',365,'Literatura obyczajowa',100,25.99 );
Insert Into BOOKS ( ID, TITLE, AUTHOR, RELEASE_DATE, NUM_OF_PAGES, GENRE, NUM_OF_COPIES, PRICE) Values ( null,'Katastroficzny początek miłości','Kinga Chmielnicka','1970-07-16',401,'Poezja',100,49.99 );
Insert Into BOOKS ( ID, TITLE, AUTHOR, RELEASE_DATE, NUM_OF_PAGES, GENRE, NUM_OF_COPIES, PRICE) Values ( null,'Obrzędy wampirów','Roman Popov','1992-11-04',481,'Fantastyka',0,39.99 );
Insert Into BOOKS ( ID, TITLE, AUTHOR, RELEASE_DATE, NUM_OF_PAGES, GENRE, NUM_OF_COPIES, PRICE) Values ( null,'On nie taki','Georgina Chapman','1972-02-01',629,'Powieść młodzieżowa',3,29.99 );
Insert Into BOOKS ( ID, TITLE, AUTHOR, RELEASE_DATE, NUM_OF_PAGES, GENRE, NUM_OF_COPIES, PRICE) Values ( null,'Loel','Abbie Fleming','2015-05-01',166,'Poezja',1,34.99 );
Insert Into BOOKS ( ID, TITLE, AUTHOR, RELEASE_DATE, NUM_OF_PAGES, GENRE, NUM_OF_COPIES, PRICE) Values ( null,'Odwróć się, kochanie','Milan Saldana','2001-08-01',289,'Horror',4,43.29 );
Insert Into BOOKS ( ID, TITLE, AUTHOR, RELEASE_DATE, NUM_OF_PAGES, GENRE, NUM_OF_COPIES, PRICE) Values ( null,'Smart and dangerous','Josiah Novikov','1968-05-02',461,'Science-fiction',0,44.49 );
Insert Into BOOKS ( ID, TITLE, AUTHOR, RELEASE_DATE, NUM_OF_PAGES, GENRE, NUM_OF_COPIES, PRICE) Values ( null,'Luke, wróć','Samson Durand','1962-02-02',369,'Romans',56,25.69 );
Insert Into BOOKS ( ID, TITLE, AUTHOR, RELEASE_DATE, NUM_OF_PAGES, GENRE, NUM_OF_COPIES, PRICE) Values ( null,'I nie mogli go odnaleźć','Natalie Lloyd','2009-11-17',599,'Kryminał',77,35.79 );
Insert Into BOOKS ( ID, TITLE, AUTHOR, RELEASE_DATE, NUM_OF_PAGES, GENRE, NUM_OF_COPIES, PRICE) Values ( null,'Tak i nie','Dominik Kwiatkowski','2022-08-05',444,'Romans',1,38.99 );
Insert Into BOOKS ( ID, TITLE, AUTHOR, RELEASE_DATE, NUM_OF_PAGES, GENRE, NUM_OF_COPIES, PRICE) Values ( null,'Niewiele zabrakło','Magdalena Kozak','2021-01-10',309,'Romans',3,44.49 );
Insert Into BOOKS ( ID, TITLE, AUTHOR, RELEASE_DATE, NUM_OF_PAGES, GENRE, NUM_OF_COPIES, PRICE) Values ( null,'Zaufałem','Homer Vazquez','2022-06-01',700,'Poezja',1,29.99 );
Insert Into BOOKS ( ID, TITLE, AUTHOR, RELEASE_DATE, NUM_OF_PAGES, GENRE, NUM_OF_COPIES, PRICE) Values ( null,'And may I rest','Caitlin Quinn','1973-09-27',634,'Poezja',0,33.49 );
Insert Into BOOKS ( ID, TITLE, AUTHOR, RELEASE_DATE, NUM_OF_PAGES, GENRE, NUM_OF_COPIES, PRICE) Values ( null,'Rodzina X','Aleksander Jankowski','2018-12-28',398,'Horror',0,45.19 );
Insert Into BOOKS ( ID, TITLE, AUTHOR, RELEASE_DATE, NUM_OF_PAGES, GENRE, NUM_OF_COPIES, PRICE) Values ( null,'Technokracja w czasach buntu','Kinga Chmielnicka','1977-11-18',417,'Science-fiction',11,45.99 );
Insert Into BOOKS ( ID, TITLE, AUTHOR, RELEASE_DATE, NUM_OF_PAGES, GENRE, NUM_OF_COPIES, PRICE) Values ( null,'Początek drogi głupców','Aleksandra Romaniuk','1995-07-02',192,'Fantastyka',20,20.99 );
Insert Into BOOKS ( ID, TITLE, AUTHOR, RELEASE_DATE, NUM_OF_PAGES, GENRE, NUM_OF_COPIES, PRICE) Values ( null,'Zaufałem podwładnemu','Owen Dominguez','1966-05-01',191,'Powieść młodzieżowa',32,19.99 );
Insert Into BOOKS ( ID, TITLE, AUTHOR, RELEASE_DATE, NUM_OF_PAGES, GENRE, NUM_OF_COPIES, PRICE) Values ( null,'Komu?','Paige Romero','2013-04-01',287,'Poezja',40,23.99 );
Insert Into BOOKS ( ID, TITLE, AUTHOR, RELEASE_DATE, NUM_OF_PAGES, GENRE, NUM_OF_COPIES, PRICE) Values ( null,'Znalezisko w Amrabacie','Homer Vazquez','2015-10-19',412,'Fantastyka',40,45.99 );
Insert Into BOOKS ( ID, TITLE, AUTHOR, RELEASE_DATE, NUM_OF_PAGES, GENRE, NUM_OF_COPIES, PRICE) Values ( null,'Odnajdź (s)pokój','Joanna Dereń','1981-01-28',656,'Literatura faktu',30,45.49 );
Insert Into BOOKS ( ID, TITLE, AUTHOR, RELEASE_DATE, NUM_OF_PAGES, GENRE, NUM_OF_COPIES, PRICE) Values ( null,'To początek jest dopiero','Paige Romero','2003-01-31',124,'Literatura obyczajowa',1,23.99 );
Insert Into BOOKS ( ID, TITLE, AUTHOR, RELEASE_DATE, NUM_OF_PAGES, GENRE, NUM_OF_COPIES, PRICE) Values ( null,'Przypadek Ernesta Brightona','Jan Drzewicki','1993-04-17',392,'Thriller',14,37.89 );
Insert Into BOOKS ( ID, TITLE, AUTHOR, RELEASE_DATE, NUM_OF_PAGES, GENRE, NUM_OF_COPIES, PRICE) Values ( null,'Kaskada','Mark Byrd','2019-05-31',370,'Literatura obyczajowa',23,55.49 );
Insert Into BOOKS ( ID, TITLE, AUTHOR, RELEASE_DATE, NUM_OF_PAGES, GENRE, NUM_OF_COPIES, PRICE) Values ( null,'Wyskok w przód','Eva Yates','2014-05-16',498,'Science-fiction',80,49.59 );
Insert Into BOOKS ( ID, TITLE, AUTHOR, RELEASE_DATE, NUM_OF_PAGES, GENRE, NUM_OF_COPIES, PRICE) Values ( null,'Hop w bok','Melissa Beck','1960-04-05',654,'Romans',0,45.99 );
Insert Into BOOKS ( ID, TITLE, AUTHOR, RELEASE_DATE, NUM_OF_PAGES, GENRE, NUM_OF_COPIES, PRICE) Values ( null,'Karmelowe przyjemności','Ibrahim Morrison','2002-05-03',387,'Literatura obyczajowa',105,13.99 );
Insert Into BOOKS ( ID, TITLE, AUTHOR, RELEASE_DATE, NUM_OF_PAGES, GENRE, NUM_OF_COPIES, PRICE) Values ( null,'Koniec puka do drzwi','Natalie Lloyd','1975-04-12',356,'Thriller',0,29.99 );
Insert Into BOOKS ( ID, TITLE, AUTHOR, RELEASE_DATE, NUM_OF_PAGES, GENRE, NUM_OF_COPIES, PRICE) Values ( null,'Za nasze grzechy','Josiah Novikov','2001-07-08',228,'Horror',11,35.99 );
Insert Into BOOKS ( ID, TITLE, AUTHOR, RELEASE_DATE, NUM_OF_PAGES, GENRE, NUM_OF_COPIES, PRICE) Values ( null,'Po co komu tyle wrażeń','Melissa Beck','2016-10-19',566,'Powieść młodzieżowa',16,34.59 );
Insert Into BOOKS ( ID, TITLE, AUTHOR, RELEASE_DATE, NUM_OF_PAGES, GENRE, NUM_OF_COPIES, PRICE) Values ( null,'Komu/czemu','Paweł Polak','2017-07-01',412,'Thriller',38,34.99 );
Insert Into BOOKS ( ID, TITLE, AUTHOR, RELEASE_DATE, NUM_OF_PAGES, GENRE, NUM_OF_COPIES, PRICE) Values ( null,'Na drodze wyboistej','Isla Dunn','1985-01-01',402,'Literatura obyczajowa',44,39.99 );
Insert Into BOOKS ( ID, TITLE, AUTHOR, RELEASE_DATE, NUM_OF_PAGES, GENRE, NUM_OF_COPIES, PRICE) Values ( null,'Obyczaje Inków','Eva Yates','2007-06-07',491,'Powieść historyczna',58,39.99 );
Insert Into BOOKS ( ID, TITLE, AUTHOR, RELEASE_DATE, NUM_OF_PAGES, GENRE, NUM_OF_COPIES, PRICE) Values ( null,'Trochę kultury','Anna Hawro','2018-09-01',213,'Powieść młodzieżowa',72,34.99 );
Insert Into BOOKS ( ID, TITLE, AUTHOR, RELEASE_DATE, NUM_OF_PAGES, GENRE, NUM_OF_COPIES, PRICE) Values ( null,'To wszystko JEGO wina','Milan Saldana','2008-06-30',292,'Literatura faktu',23,45.99 );
Insert Into BOOKS ( ID, TITLE, AUTHOR, RELEASE_DATE, NUM_OF_PAGES, GENRE, NUM_OF_COPIES, PRICE) Values ( null,'Tomik poezji 2019','Kinga Chmielnicka','2020-02-28',144,'Poezja',14,34.99 );
Insert Into BOOKS ( ID, TITLE, AUTHOR, RELEASE_DATE, NUM_OF_PAGES, GENRE, NUM_OF_COPIES, PRICE) Values ( null,'To the moon','Mark Byrd','1999-02-09',467,'Science-fiction',45,27.89 );
Insert Into BOOKS ( ID, TITLE, AUTHOR, RELEASE_DATE, NUM_OF_PAGES, GENRE, NUM_OF_COPIES, PRICE) Values ( null,'Aż na ziemię','Scott Wilkinson','1961-04-01',197,'Literatura faktu',1,27.99 );
Insert Into BOOKS ( ID, TITLE, AUTHOR, RELEASE_DATE, NUM_OF_PAGES, GENRE, NUM_OF_COPIES, PRICE) Values ( null,'Zachmurzone niebo o północy','Eloise Arnold','1998-05-19',254,'Poezja',4,28.89 );
Insert Into BOOKS ( ID, TITLE, AUTHOR, RELEASE_DATE, NUM_OF_PAGES, GENRE, NUM_OF_COPIES, PRICE) Values ( null,'Zapytaj go o nic','Adam Rzepa','1986-01-21',535,'Fantastyka',22,38.89 );
Insert Into BOOKS ( ID, TITLE, AUTHOR, RELEASE_DATE, NUM_OF_PAGES, GENRE, NUM_OF_COPIES, PRICE) Values ( null,'Mali grzesznicy','Mohammad Stone','2018-02-10',296,'Thriller',2,38.99 );
Insert Into BOOKS ( ID, TITLE, AUTHOR, RELEASE_DATE, NUM_OF_PAGES, GENRE, NUM_OF_COPIES, PRICE) Values ( null,'Straciłem wiarę w lepsze czasy','Traci Bowen','1974-02-18',329,'Kryminał',0,37.79 );
Insert Into BOOKS ( ID, TITLE, AUTHOR, RELEASE_DATE, NUM_OF_PAGES, GENRE, NUM_OF_COPIES, PRICE) Values ( null,'Kosmopułapka','Zara Martinez','2020-06-06',531,'Science-fiction',7,50.99 );
Insert Into BOOKS ( ID, TITLE, AUTHOR, RELEASE_DATE, NUM_OF_PAGES, GENRE, NUM_OF_COPIES, PRICE) Values ( null,'Gremthorn','Maryam Park','2022-04-05',438,'Fantastyka',10,49.49 );
Insert Into BOOKS ( ID, TITLE, AUTHOR, RELEASE_DATE, NUM_OF_PAGES, GENRE, NUM_OF_COPIES, PRICE) Values ( null,'Największy spośród tłumu','Natalie Lloyd','2022-01-15',430,'Powieść historyczna',36,36.49 );
Insert Into BOOKS ( ID, TITLE, AUTHOR, RELEASE_DATE, NUM_OF_PAGES, GENRE, NUM_OF_COPIES, PRICE) Values ( null,'Nikt nie musi wiedzieć','Simon Michel','2019-08-01',697,'Science-fiction',1,35.49 );
Insert Into BOOKS ( ID, TITLE, AUTHOR, RELEASE_DATE, NUM_OF_PAGES, GENRE, NUM_OF_COPIES, PRICE) Values ( null,'Kto pytał?','Samson Durand','1989-08-30',469,'Powieść młodzieżowa',0,49.99 );
Insert Into BOOKS ( ID, TITLE, AUTHOR, RELEASE_DATE, NUM_OF_PAGES, GENRE, NUM_OF_COPIES, PRICE) Values ( null,'ktoś kogoś','Scott Wilkinson','2022-10-11',295,'Poezja',81,71.99 );
Insert Into BOOKS ( ID, TITLE, AUTHOR, RELEASE_DATE, NUM_OF_PAGES, GENRE, NUM_OF_COPIES, PRICE) Values ( null,'Hasło - biurokracja','Owen Dominguez','2021-07-14',607,'Powieść historyczna',1,29.99 );
Insert Into BOOKS ( ID, TITLE, AUTHOR, RELEASE_DATE, NUM_OF_PAGES, GENRE, NUM_OF_COPIES, PRICE) Values ( null,'Stalin na drodze gniewu','Adam Rzepa','2017-06-17',348,'Literatura faktu',9,69.99 );
Insert Into BOOKS ( ID, TITLE, AUTHOR, RELEASE_DATE, NUM_OF_PAGES, GENRE, NUM_OF_COPIES, PRICE) Values ( null,'Zbrodnie biura klasy średniej','Josiah Novikov','2014-01-31',144,'Science-fiction',0,69.99 );
Insert Into BOOKS ( ID, TITLE, AUTHOR, RELEASE_DATE, NUM_OF_PAGES, GENRE, NUM_OF_COPIES, PRICE) Values ( null,'Kaszmirowo-purpurowe','Eva Yates','1967-08-19',418,'Thriller',1,34.99 );
Insert Into BOOKS ( ID, TITLE, AUTHOR, RELEASE_DATE, NUM_OF_PAGES, GENRE, NUM_OF_COPIES, PRICE) Values ( null,'Na co komu jego życie','Mohammad Stone','1981-07-17',664,'Kryminał',11,44.99 );
Insert Into BOOKS ( ID, TITLE, AUTHOR, RELEASE_DATE, NUM_OF_PAGES, GENRE, NUM_OF_COPIES, PRICE) Values ( null,'Hipernowa','Anna Hawro','2011-01-01',273,'Science-fiction',58,39.89 );
Insert Into BOOKS ( ID, TITLE, AUTHOR, RELEASE_DATE, NUM_OF_PAGES, GENRE, NUM_OF_COPIES, PRICE) Values ( null,'Kolacja u rodziny','Joanna Dereń','1972-06-01',380,'Powieść młodzieżowa',114,45.59 );
Insert Into BOOKS ( ID, TITLE, AUTHOR, RELEASE_DATE, NUM_OF_PAGES, GENRE, NUM_OF_COPIES, PRICE) Values ( null,'Władcy urodzaju','Maryam Park','1994-05-31',689,'Fantastyka',2,34.59 );
Insert Into BOOKS ( ID, TITLE, AUTHOR, RELEASE_DATE, NUM_OF_PAGES, GENRE, NUM_OF_COPIES, PRICE) Values ( null,'Kości poległych Rzymian','Helen Buchanan','1970-08-01',175,'Literatura faktu',1,18.99 );
Insert Into BOOKS ( ID, TITLE, AUTHOR, RELEASE_DATE, NUM_OF_PAGES, GENRE, NUM_OF_COPIES, PRICE) Values ( null,'Casa','Joanna Dereń','2018-08-01',647,'Poezja',0,17.89 );
Insert Into BOOKS ( ID, TITLE, AUTHOR, RELEASE_DATE, NUM_OF_PAGES, GENRE, NUM_OF_COPIES, PRICE) Values ( null,'Dom tajemnic','Isla Dunn','1966-12-01',480,'Kryminał',15,15.99 );
Insert Into BOOKS ( ID, TITLE, AUTHOR, RELEASE_DATE, NUM_OF_PAGES, GENRE, NUM_OF_COPIES, PRICE) Values ( null,'Wybiórczość','Marie Knight','2015-01-07',545,'Kryminał',71,14.99 );
Insert Into BOOKS ( ID, TITLE, AUTHOR, RELEASE_DATE, NUM_OF_PAGES, GENRE, NUM_OF_COPIES, PRICE) Values ( null,'Podejrzyj mnie','Anastazja Lis','1962-05-01',241,'Kryminał',34,34.59 );
Insert Into BOOKS ( ID, TITLE, AUTHOR, RELEASE_DATE, NUM_OF_PAGES, GENRE, NUM_OF_COPIES, PRICE) Values ( null,'Czerwone smugi','Mohammad Stone','2018-10-01',649,'Literatura obyczajowa',20,24.59 );
Insert Into BOOKS ( ID, TITLE, AUTHOR, RELEASE_DATE, NUM_OF_PAGES, GENRE, NUM_OF_COPIES, PRICE) Values ( null,'Czekoladowy smak jej ust','Bruno Mazur','2001-11-05',609,'Romans',12,89.99 );
Insert Into BOOKS ( ID, TITLE, AUTHOR, RELEASE_DATE, NUM_OF_PAGES, GENRE, NUM_OF_COPIES, PRICE) Values ( null,'Ku przyszłości','Joanna Dereń','2022-02-22',384,'Literatura faktu',3,31.99 );
Insert Into BOOKS ( ID, TITLE, AUTHOR, RELEASE_DATE, NUM_OF_PAGES, GENRE, NUM_OF_COPIES, PRICE) Values ( null,'Niebieskie niebo i ty','Homer Vazquez','2022-06-01',330,'Romans',90,31.59 );
Insert Into BOOKS ( ID, TITLE, AUTHOR, RELEASE_DATE, NUM_OF_PAGES, GENRE, NUM_OF_COPIES, PRICE) Values ( null,'Uptown','Paige Romero','2021-11-13',524,'Science-fiction',54,104.59 );
Insert Into BOOKS ( ID, TITLE, AUTHOR, RELEASE_DATE, NUM_OF_PAGES, GENRE, NUM_OF_COPIES, PRICE) Values ( null,'Rok ku końcowi','Melissa Beck','2022-02-01',499,'Science-fiction',14,115.99 );
Insert Into BOOKS ( ID, TITLE, AUTHOR, RELEASE_DATE, NUM_OF_PAGES, GENRE, NUM_OF_COPIES, PRICE) Values ( null,'Arrivederci, książę','Summer Padilla','2010-10-10',400,'Horror',6,15.99 );
Insert Into BOOKS ( ID, TITLE, AUTHOR, RELEASE_DATE, NUM_OF_PAGES, GENRE, NUM_OF_COPIES, PRICE) Values ( null,'Zapomniana dynastia','Scott Wilkinson','1963-04-01',671,'Powieść historyczna',5,25.99 );
Insert Into BOOKS ( ID, TITLE, AUTHOR, RELEASE_DATE, NUM_OF_PAGES, GENRE, NUM_OF_COPIES, PRICE) Values ( null,'Kres dni','Caitlin Quinn','1962-11-11',370,'Poezja',1,74.59 );
Insert Into BOOKS ( ID, TITLE, AUTHOR, RELEASE_DATE, NUM_OF_PAGES, GENRE, NUM_OF_COPIES, PRICE) Values ( null,'Z faktami się nie dyskutuje','Oliwia Mazurkiewicz','1999-01-12',546,'Literatura faktu',0,55.49 );
Insert Into BOOKS ( ID, TITLE, AUTHOR, RELEASE_DATE, NUM_OF_PAGES, GENRE, NUM_OF_COPIES, PRICE) Values ( null,'Kino po zmroku','Eloise Arnold','1988-09-01',343,'Horror',43,29.29 );